In [2]:
#import numpy as np

#data = np.load(r"/home/rosario/explainable/Bachelor/Results/Num_Epochs_5batchSize_42023-01-14_172750/featureListALL.npz")
#a = data["featureListALL"][0]
#for i in a:
#    if i != 0.0 and i != 1.0: 
#        print(repr(np.float64(i)))
        

In [5]:
import numpy as np

trainingResults = np.load#("./WorkingResults/Trainingresults/data.npz")
rulesResults = np.load("./WorkingResults/rulesResults/discriminative_rules/_2023-07-21_10:45:16.npz")

for i in trainingResults:
    print(i)
print("----")






SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape (654512833.py, line 4)

In [ ]:
for i in rulesResults:
    print(i)

rules_list_overIterations
labelList_rules_overIterations
rulePrecisionList_overIterations
predictionComparisonList_overIterations
rulesComplexityList_overIterations
coverageList_overIterations
ruleSupportList_overIterations
numberOfGeneratedRules_overIterations
jaccardSimilarity_overIterations
cosineSimilarity_overIterations
overlapSimilarity_overIterations
diceSimilarity_overIterations
raw_rules_overIterations
numberOfGeneratedRulesRAW_overIterations
trackedRules_OHE


In [92]:
#changes binnned in n_sized bins 
    # count how often the apprearance of a rule has changed over iterations 
import numpy as np
trackedRules_OHE  = np.array([[1,0,1,1,1,1,0,0,1],
                                  [0,0,0,0,0,0,0,0,1],
                                  [0,0,0,0,1,1,0,0,0]])

def getchangeTrackerList(trackedRules_OHE):
    #transpore
    trackedRules_OHE = np.array(trackedRules_OHE).transpose()

    #now we have over the rows the iterarations  
    # and over the colums the rules   
    """
        iterations   -> 
        [[1 1 1 0 0]
      ^ [1 0 0 1 0]
      | [0 1 1 0 1]]
    rules list

    
    """
    trackedRules_OHE  = np.array([[1,0,1,1,1,1,0,0,1],
                                  [0,0,0,0,0,0,0,0,1],
                                  [0,0,0,0,1,1,0,0,0]])
    changeTrackerList =[]
    for i in trackedRules_OHE:
        temp = -1
        changeTracker = []
        for j in range(len(i)):
            #if i[j] != 0:
                if i[j] != temp:
                    changeTracker.append(1)
                    temp = i[j]
                else:
                    changeTracker.append(0)
                    temp = i[j]
        changeTrackerList.append(changeTracker)

    return changeTrackerList

changeTrackerList = getchangeTrackerList("as")#(rulesResults["trackedRules_OHE"])

#print(changeTrackerList)
#print(len(changeTrackerList))

trackedRules_OHE  = [[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],]
                                  
print(trackedRules_OHE)
def countConsequtiveRuleApperance(trackedRules_OHE,n):
    ruleAtIterationIsImportant_List = []
    for i in trackedRules_OHE:
        #print(i)
        ruleAtIterationIsImportant =[]
        for j in range(0,len(i)):
            print("j")
            print(j)

            
            #print(j)
           # print(n)
           # print(j<=n)
            if j < n -1:
                #print("ok?")
                ruleAtIterationIsImportant.append(0) #0 is not important | cause n iterations not reached yet
            elif j > (len(i) -n):
                ruleAtIterationIsImportant.append(0)
            else:
                tempConsequentApperanceCounter = i[j:j+n].count(1)
                #print("a")
                print(tempConsequentApperanceCounter)
                print(i[j:j+n].count(1))
                #print("aaaa")
                #print(tempConsequentApperanceCounter)
                if tempConsequentApperanceCounter == n:
                    print("asasasdaas")
                    ruleAtIterationIsImportant.append(1) # is imortant at iteration
                else:
                    ruleAtIterationIsImportant.append(0)
        #print(ruleAtIterationIsImportant)
        ruleAtIterationIsImportant_List.append(ruleAtIterationIsImportant)

    return ruleAtIterationIsImportant_List

countConsequtiveRuleApperance(trackedRules_OHE,3)
         

[[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1]]
j
0
j
1
j
2
3
3
asasasdaas
j
3
3
3
asasasdaas
j
4
3
3
asasasdaas
j
5
3
3
asasasdaas
j
6
3
3
asasasdaas
j
7
j
8
j
0
j
1
j
2
3
3
asasasdaas
j
3
3
3
asasasdaas
j
4
3
3
asasasdaas
j
5
3
3
asasasdaas
j
6
3
3
asasasdaas
j
7
j
8
j
0
j
1
j
2
3
3
asasasdaas
j
3
3
3
asasasdaas
j
4
3
3
asasasdaas
j
5
3
3
asasasdaas
j
6
3
3
asasasdaas
j
7
j
8


[[0, 0, 1, 1, 1, 1, 1, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 0, 0]]

In [ ]:
featureListALL= data["featureListALL"]
featureListALL0= data["featureListALL_0"]

training_acc = data["training_acc"]

#600 trainingdatapoints 
print(len(featureListALL[0]))
sizeDS = 455
for i in range(300):
    #print(featureListALL[0][0:4])
    print(featureListALL[0][i*sizeDS:i*sizeDS +6])
    print(featureListALL0[0][i*sizeDS:i*sizeDS +6])

# optimizer.step() after optimizer.zero_grad()

227500
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801519 -0.00801519]
[-0.00698141 -0.00850374 -0.008

In [ ]:
data =np.load("/home/rosario/explainable/Bachelor/test/Results/seedNum_0_BinaryClassification_KaggleDiabetesALL_Num_Epochs_500batchSize_4_0.001_2023-02-02_131052/data.npz")

for i in data:
    print(i)

featureListALL= data["featureListALL"]
featureListALL0= data["featureListALL_0"]

training_acc = data["training_acc"]

#600 trainingdatapoints 
print(len(featureListALL[0]))
sizeDS = 455
for i in range(300):
    #print(featureListALL[0][0:4])
    print(featureListALL[0][i*sizeDS:i*sizeDS +6])
    print(featureListALL0[0][i*sizeDS:i*sizeDS +6])



featureListALL
featureListALL_0
training_acc
test_acc
training_loss_epoch
training_loss_batch
test_loss_epoch
test_loss_batch
227500
[-0.00698076 -0.0085027  -0.00801412 -0.00801412 -0.00800764 -0.00800764]
[-0.00698141 -0.00850374 -0.00801519 -0.00801519 -0.00801412 -0.00801412]
[-0.00670403 -0.00670905 -0.00619547 -0.00759588 -0.00758976 -0.00758976]
[-0.00670447 -0.00670954 -0.00619596 -0.00759663 -0.00759588 -0.00759588]
[-0.0065961  -0.00643485 -0.00539484 -0.0072094  -0.00720358 -0.00720358]
[-0.00659637 -0.00643515 -0.00539516 -0.00720986 -0.0072094  -0.0072094 ]
[-0.00635397 -0.00617552 -0.00511766 -0.00562402 -0.00684532 -0.00684532]
[-0.00635408 -0.00617565 -0.00511777 -0.0056241  -0.00685089 -0.00685089]
[-0.0019936  -0.00455154 -0.00118515 -0.00276023  0.00183943 -0.00276419]
[-0.00199368 -0.00455161 -0.00118526 -0.00276038  0.00184444 -0.00276023]
[-0.00219194 -0.00226218 -0.00140919 -0.00298498  0.00022611 -0.00298882]
[-0.00219222 -0.00226247 -0.00140952 -0.0029853   0.0